### ISSUE TITLE
Xcode9ビルドでCarthage経由でコンパイルができない

### ISSUE THREAD

**Issue by shogo4405** [malt03/DebugMenuRealmBrowser#2]
xcode9を利用した環境で以下のcarthageを利用したところエラーがでてとまりました。

```
$ carthage update --platform iOS --no-use-binaries
```

レポジトリを確認したところ、
https://github.com/malt03/DebugMenuRealmBrowser/tree/master/Example/DebugMenuRealmBrowser.xcodeproj 内で、

RealmSwift2.8.0を利用しているのが原因でコンパイルが止まっていました。XCode9対応版は2.8.3からです。
https://github.com/realm/realm-cocoa/pull/5006

**Comment by shogo4405** [comment]
手元で pod updateしてコンパイルできるようになったことを確認しました。
https://github.com/shogo4405/DebugMenuRealmBrowser/tree/feature/support-xcode9

**Comment by shogo4405** [comment]
1.0.0で無事利用できること確認しました。
ありがとうございますmm

**Comment by malt03** [comment]
対応しました〜
